export * from './app-toolbar/app-toolbar.component';
export * from './app-navbar/app-navbar.component';
export * from './app-footer/app-footer.component';
export * from './main/main.component';
export * from './about/about.component';
export * from './catalog/catalog.component';
export * from './price/price.component';
export * from './blog/blog.component';
export * from './contacts/contacts.component';
